In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

Affine Maps

In [7]:
lin = nn.Linear(5,3) # (input_dimension, output_dimension)
data = autograd.Variable(torch.randn(2,5)) # (batch_size, input_dimension)
print(lin(data))

tensor([[ 0.2980,  0.6653,  0.9296],
        [-0.0303, -0.6826,  0.2214]], grad_fn=<AddmmBackward>)


### Non-Linearities

#### torch.functional에 대하여
: 파라미터가 없다. 즉, 학습 중에 업데이트될 가중치가 없다.

In [10]:
data = autograd.Variable(torch.randn(2,2))
print(data)
print(F.relu(data))

tensor([[-2.1355e+00, -1.5609e-03],
        [ 1.0415e+00,  8.0915e-01]])
tensor([[0.0000, 0.0000],
        [1.0415, 0.8091]])


### softmax

In [11]:
data = autograd.Variable(torch.randn(5))
print(data)
print(F.softmax(data, dim=0))
print(F.softmax(data, dim=0).sum())
print(F.log_softmax(data,dim=0))

tensor([ 0.5292, -0.0445,  0.0581,  0.8505, -1.0904])
tensor([0.2656, 0.1497, 0.1658, 0.3663, 0.0526])
tensor(1.)
tensor([-1.3257, -1.8993, -1.7967, -1.0043, -2.9453])
