In [1]:
import torch

### Tensor 생성

In [3]:
# 초기화되지 않은 5*3 행렬 생성
x = torch.Tensor(5,3)
# x = torch.empty(5,3)과 비슷한 기능
print(x)

tensor([[1.0653e-38, 1.0194e-38, 8.4490e-39],
        [9.2756e-39, 1.0837e-38, 1.0102e-38],
        [1.0286e-38, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39]])


In [3]:
# [5, 3] 자체가 텐서로 들어간 모양새와 구분하자
torch.Tensor([5,3])

tensor([5., 3.])

In [4]:
# 무작위로 초기화된 5*3 행렬 생성
x = torch.rand(5,3)
print(x)

tensor([[0.6646, 0.1925, 0.2916],
        [0.3201, 0.2117, 0.7948],
        [0.3128, 0.8482, 0.7526],
        [0.5321, 0.1416, 0.1139],
        [0.7979, 0.6609, 0.7841]])


In [5]:
# 텐서 사이즈 확인은 .size()로
print(x.size())

torch.Size([5, 3])


### 연산

In [6]:
# 더하기도 됨
y = torch.rand(5,3)
print(y)
print(x+y)

tensor([[0.6614, 0.1211, 0.4186],
        [0.9318, 0.0514, 0.1202],
        [0.0592, 0.2944, 0.6437],
        [0.6458, 0.0667, 0.7189],
        [0.0156, 0.4233, 0.7938]])
tensor([[1.3261, 0.3137, 0.7102],
        [1.2519, 0.2632, 0.9149],
        [0.3720, 1.1426, 1.3963],
        [1.1779, 0.2084, 0.8327],
        [0.8135, 1.0842, 1.5780]])


In [7]:
# add 함수를 이용해도 더하기 됨
print(torch.add(x, y))

tensor([[1.3261, 0.3137, 0.7102],
        [1.2519, 0.2632, 0.9149],
        [0.3720, 1.1426, 1.3963],
        [1.1779, 0.2084, 0.8327],
        [0.8135, 1.0842, 1.5780]])


In [8]:
# tensor의 형태를 미리 설정하고 더하기도 됨
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3261, 0.3137, 0.7102],
        [1.2519, 0.2632, 0.9149],
        [0.3720, 1.1426, 1.3963],
        [1.1779, 0.2084, 0.8327],
        [0.8135, 1.0842, 1.5780]])


In [9]:
# result의 형태를 아무렇게나 지정해줘도 되네??
result = torch.Tensor([100])
torch.add(x, y, out=result)
print(result) 

tensor([[1.3261, 0.3137, 0.7102],
        [1.2519, 0.2632, 0.9149],
        [0.3720, 1.1426, 1.3963],
        [1.1779, 0.2084, 0.8327],
        [0.8135, 1.0842, 1.5780]])


In [10]:
# 위의 셀과 아래의 계산 결과는 다르지 않지만, 위에서 out이 지정이 되지 않으면
# a freshly-allocated array is returned.
# 메모리 사용 측면에서 차이가 있다.

result = torch.add(x, y)
print(result)

tensor([[1.3261, 0.3137, 0.7102],
        [1.2519, 0.2632, 0.9149],
        [0.3720, 1.1426, 1.3963],
        [1.1779, 0.2084, 0.8327],
        [0.8135, 1.0842, 1.5780]])


In [11]:
# y자체를 x+y의 값으로 업데이트
y.add_(x)
print(y)

tensor([[1.3261, 0.3137, 0.7102],
        [1.2519, 0.2632, 0.9149],
        [0.3720, 1.1426, 1.3963],
        [1.1779, 0.2084, 0.8327],
        [0.8135, 1.0842, 1.5780]])


In [12]:
print(x)

tensor([[0.6646, 0.1925, 0.2916],
        [0.3201, 0.2117, 0.7948],
        [0.3128, 0.8482, 0.7526],
        [0.5321, 0.1416, 0.1139],
        [0.7979, 0.6609, 0.7841]])


### 인덱스로 호출

In [13]:
# 넘파이 행렬과 비슷하게 슬라이싱 가능
print(x[:,1])

tensor([0.1925, 0.2117, 0.8482, 0.1416, 0.6609])


### resize

In [14]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Torch Tensor -> NumPy array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
# a의 값에 조작을 가하면 b의 값에도 영향이 간다!
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### NumPy array -> Torch Tensor

In [18]:
# 마찬가지로 a의 값에 조작을 가하면 b의 값에도 영향이 간다!
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
