In [1]:
import torch
from torch.autograd import Variable

In [7]:
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [8]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [9]:
print(y.grad_fn)

In [10]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [11]:
out.backward()

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

In [21]:
x

tensor([ 0.9186, -0.0196,  0.2543], requires_grad=True)

In [24]:
y = x*2
y.data.norm()

tensor(1.9067)

In [25]:
y = x*2
while y.data.norm() <1000:
    y=y*2
    print(y)
# print(y)

tensor([ 3.6745, -0.0784,  1.0172], grad_fn=<MulBackward0>)
tensor([ 7.3489, -0.1568,  2.0344], grad_fn=<MulBackward0>)
tensor([14.6978, -0.3135,  4.0689], grad_fn=<MulBackward0>)
tensor([29.3956, -0.6271,  8.1378], grad_fn=<MulBackward0>)
tensor([58.7912, -1.2542, 16.2755], grad_fn=<MulBackward0>)
tensor([117.5825,  -2.5083,  32.5510], grad_fn=<MulBackward0>)
tensor([235.1649,  -5.0167,  65.1020], grad_fn=<MulBackward0>)
tensor([470.3299, -10.0334, 130.2041], grad_fn=<MulBackward0>)
tensor([940.6598, -20.0667, 260.4082], grad_fn=<MulBackward0>)
tensor([1881.3196,  -40.1335,  520.8163], grad_fn=<MulBackward0>)


In [26]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])
